# Generated by Django 5.2.6 on 2025-09-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_management', '0002_alter_authuser_birth_date_alter_authuser_gender_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='gender_code',
            field=models.SmallIntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')]),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='native_language',
            field=models.CharField(choices=[('af', 'Afrikaans'), ('am', 'Amharic'), ('ar', 'Arabic'), ('as', 'Assamese'), ('az', 'Azerbaijani'), ('ba', 'Bashkir'), ('be', 'Belarusian'), ('bg', 'Bulgarian'), ('bho', 'Bhojpuri'), ('bn', 'Bengali'), ('bo', 'Tibetan'), ('brx', 'Bodo'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('doi', 'Dogri'), ('dsb', 'Lowersorbian'), ('dv', 'Divehi'), ('el', 'Greek'), ('en', 'English'), ('es', 'Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fil', 'Filipino'), ('fj', 'Fijian'), ('fo', 'Faroese'), ('fr', 'French'), ('fr-CA', 'French Canada'), ('ga', 'Irish'), ('gl', 'Galician'), ('gom', 'Konkani'), ('gu', 'Gujarati'), ('ha', 'Hausa'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hne', 'Chhattisgarhi'), ('hr', 'Croatian'), ('hsb', 'Uppersorbian'), ('ht', 'Haitiancreole'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('id', 'Indonesian'), ('ig', 'Igbo'), ('ikt', 'Inuinnaqtun'), ('is', 'Icelandic'), ('it', 'Italian'), ('iu', 'Inuktitut'), ('iu-Latn', 'Inuktitut Latin'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kmr', 'Kurdish Northern'), ('kn', 'Kannada'), ('ko', 'Korean'), ('ks', 'Kashmiri'), ('ku', 'Kurdish Central'), ('ky', 'Kyrgyz'), ('lb', 'Luxembourgish'), ('ln', 'Lingala'), ('lo', 'Lao'), ('lt', 'Lithuanian'), ('lug', 'Ganda'), ('lv', 'Latvian'), ('lzh', 'Chinese Literary'), ('mai', 'Maithili'), ('mg', 'Malagasy'), ('mi', 'Maori'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn-Cyrl', 'Mongolian Cyrillic'), ('mn-Mong', 'Mongolian Traditional'), ('mni', 'Manipuri'), ('mr', 'Marathi'), ('ms', 'Malay'), ('mt', 'Maltese'), ('mww', 'Hmongdaw'), ('my', 'Myanmar Burmese'), ('nb', 'Norwegian'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nso', 'Sesothosaleboa'), ('nya', 'Nyanja'), ('or', 'Odia'), ('otq', 'Queretarootomi'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('prs', 'Dari'), ('ps', 'Pashto'), ('pt', 'Portuguese Brazil'), ('pt-PT', 'Portuguese Portugal'), ('ro', 'Romanian'), ('ru', 'Russian'), ('run', 'Rundi'), ('rw', 'Kinyarwanda'), ('sd', 'Sindhi'), ('si', 'Sinhala'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sm', 'Samoan'), ('sn', 'Shona'), ('so', 'Somali'), ('sq', 'Albanian'), ('sr-Cyrl', 'Serbian Cyrillic'), ('sr-Latn', 'Serbian Latin'), ('st', 'Sesoth'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('th', 'Thai'), ('ti', 'Tigrinya'), ('tk', 'Turkmen'), ('tlh-Latn', 'Klingon Latin'), ('tlh-Piqd', 'Klingon Piqad'), ('tn', 'Setswana'), ('to', 'Tongan'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('ty', 'Tahitian'), ('ug', 'Uyghur'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek Latin'), ('vi', 'Vietnamese'), ('xh', 'Xhosa'), ('yo', 'Yoruba'), ('yua', 'Yucatecmaya'), ('yue', 'Cantonese Traditional'), ('zh-Hans', 'Chinese Simplified'), ('zh-Hant', 'Chinese Traditional'), ('zu', 'Zulu')], help_text='모국어(iso 639)', max_length=20),
        ),
    ]
