# Generated by Django 5.2.6 on 2025-09-16 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_management', '0003_alter_authuser_birth_date_alter_authuser_gender_code_and_more'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='지역 코드(KR)', max_length=50)),
                ('level', models.SmallIntegerField(choices=[(0, 'Country'), (1, 'Province'), (2, 'City')])),
                ('ko', models.CharField(help_text='한국어 이름', max_length=255)),
                ('en', models.CharField(help_text='영문 이름', max_length=255)),
                ('ja', models.CharField(help_text='일본어 이름', max_length=255)),
                ('parent_id', models.PositiveBigIntegerField(blank=True, help_text='상위 지역 ID', null=True)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Region list',
            },
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='main_global_region_id',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='main_local_region_id',
        ),
        migrations.AlterField(
            model_name='authuser',
            name='native_language',
            field=models.CharField(choices=[('af', 'Afrikaans'), ('am', 'Amharic'), ('ar', 'Arabic'), ('as', 'Assamese'), ('az', 'Azerbaijani'), ('ba', 'Bashkir'), ('be', 'Belarusian'), ('bg', 'Bulgarian'), ('bho', 'Bhojpuri'), ('bn', 'Bengali'), ('bo', 'Tibetan'), ('brx', 'Bodo'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('doi', 'Dogri'), ('dsb', 'Lowersorbian'), ('dv', 'Divehi'), ('el', 'Greek'), ('en', 'English'), ('es', 'Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fil', 'Filipino'), ('fj', 'Fijian'), ('fo', 'Faroese'), ('fr', 'French'), ('fr-CA', 'French Canada'), ('ga', 'Irish'), ('gl', 'Galician'), ('gom', 'Konkani'), ('gu', 'Gujarati'), ('ha', 'Hausa'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hne', 'Chhattisgarhi'), ('hr', 'Croatian'), ('hsb', 'Uppersorbian'), ('ht', 'Haitiancreole'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('id', 'Indonesian'), ('ig', 'Igbo'), ('ikt', 'Inuinnaqtun'), ('is', 'Icelandic'), ('it', 'Italian'), ('iu', 'Inuktitut'), ('iu-Latn', 'Inuktitut Latin'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kmr', 'Kurdish Northern'), ('kn', 'Kannada'), ('ko', 'Korean'), ('ks', 'Kashmiri'), ('ku', 'Kurdish Central'), ('ky', 'Kyrgyz'), ('lb', 'Luxembourgish'), ('ln', 'Lingala'), ('lo', 'Lao'), ('lt', 'Lithuanian'), ('lug', 'Ganda'), ('lv', 'Latvian'), ('lzh', 'Chinese Literary'), ('mai', 'Maithili'), ('mg', 'Malagasy'), ('mi', 'Maori'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn-Cyrl', 'Mongolian Cyrillic'), ('mn-Mong', 'Mongolian Traditional'), ('mni', 'Manipuri'), ('mr', 'Marathi'), ('ms', 'Malay'), ('mt', 'Maltese'), ('mww', 'Hmongdaw'), ('my', 'Myanmar Burmese'), ('nb', 'Norwegian'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nso', 'Sesothosaleboa'), ('nya', 'Nyanja'), ('or', 'Odia'), ('otq', 'Queretarootomi'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('prs', 'Dari'), ('ps', 'Pashto'), ('pt', 'Portuguese Brazil'), ('pt-PT', 'Portuguese Portugal'), ('ro', 'Romanian'), ('ru', 'Russian'), ('run', 'Rundi'), ('rw', 'Kinyarwanda'), ('sd', 'Sindhi'), ('si', 'Sinhala'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sm', 'Samoan'), ('sn', 'Shona'), ('so', 'Somali'), ('sq', 'Albanian'), ('sr-Cyrl', 'Serbian Cyrillic'), ('sr-Latn', 'Serbian Latin'), ('st', 'Sesoth'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('th', 'Thai'), ('ti', 'Tigrinya'), ('tk', 'Turkmen'), ('tlh-Latn', 'Klingon Latin'), ('tlh-Piqd', 'Klingon Piqad'), ('tn', 'Setswana'), ('to', 'Tongan'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('ty', 'Tahitian'), ('ug', 'Uyghur'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek Latin'), ('vi', 'Vietnamese'), ('xh', 'Xhosa'), ('yo', 'Yoruba'), ('yua', 'Yucatecmaya'), ('yue', 'Cantonese Traditional'), ('zh-Hans', 'Chinese Simplified'), ('zh-Hant', 'Chinese Traditional'), ('zu', 'Zulu')], help_text='모국어(iso 639)', max_length=50),
        ),
        migrations.CreateModel(
            name='UserAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='파일 경로', max_length=500)),
                ('is_primary', models.BooleanField(default=False, help_text='썸네일 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_avatars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Avatar',
                'verbose_name_plural': 'User Avatar list',
            },
        ),
        migrations.CreateModel(
            name='UserRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_type', models.SmallIntegerField(choices=[(0, 'Local'), (1, 'Global')])),
                ('move_in_date', models.DateField(help_text='이동 일시')),
                ('duration_months', models.PositiveSmallIntegerField(blank=True, help_text='거주 기간(개월)', null=True)),
                ('occupation_detail', models.CharField(blank=True, help_text='상세 설명', max_length=100, null=True)),
                ('occupation_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_regions', to='categories.occupationtype')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_regions', to='auth_management.regions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_regions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Region',
                'verbose_name_plural': 'User Region list',
            },
        ),
        migrations.AddField(
            model_name='authuser',
            name='main_global_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_global_region', to='auth_management.userregion'),
        ),
        migrations.AddField(
            model_name='authuser',
            name='main_local_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_local_region', to='auth_management.userregion'),
        ),
    ]
