# Generated by Django 5.2.6 on 2025-09-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_management', '0004_regions_remove_authuser_main_global_region_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regions',
            name='level',
            field=models.SmallIntegerField(choices=[(0, 'Nation'), (1, 'Province'), (2, 'City')]),
        ),
    ]
