# Generated by Django 5.2.6 on 2025-09-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_management', '0005_alter_regions_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='profile_thumbnail_url',
            field=models.URLField(blank=True, help_text='프로필 썸네일 URL', null=True),
        ),
    ]
