# Generated by Django 5.2.6 on 2025-09-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='지역 코드(KR)', max_length=50)),
                ('level', models.SmallIntegerField(choices=[(0, 'Nation'), (1, 'Province'), (2, 'City')])),
                ('ko', models.CharField(help_text='한국어 이름', max_length=255)),
                ('en', models.CharField(help_text='영문 이름', max_length=255)),
                ('ja', models.CharField(help_text='일본어 이름', max_length=255)),
                ('parent_id', models.PositiveBigIntegerField(blank=True, help_text='상위 지역 ID', null=True)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Region list',
            },
        ),
    ]
