# Generated by Django 5.2.6 on 2025-09-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OccupationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_type', models.SmallIntegerField(choices=[(0, 'Local'), (1, 'Global')])),
                ('code', models.CharField(help_text='코드(STUDENT, EMPLOYEE, RETIRED, UNEMPLOYED, HOMEMAKER, OTHER)', max_length=50)),
                ('ko', models.CharField(blank=True, help_text='한국어', max_length=50, null=True)),
                ('en', models.CharField(blank=True, help_text='영문', max_length=50, null=True)),
                ('ja', models.CharField(blank=True, help_text='일본어', max_length=50, null=True)),
                ('order', models.PositiveSmallIntegerField(help_text='순서')),
                ('is_active', models.BooleanField(default=True, help_text='활성 여부')),
            ],
            options={
                'verbose_name': 'Occupation Type',
                'verbose_name_plural': 'Occupation Type list',
            },
        ),
    ]
